AWSTemplateFormatVersion: 2010-09-09
Description: >
  Amazon Connect Cloud Contact Center Backup and Restore Operations

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "AWS Account Configuration"
        Parameters:
          - AmazonAccountType
          - AmazonTargetAccount
          - AmazonTargetAccountRegion
      - 
        Label:
          default: "DynamoDB Table Configuration"
        Parameters:
          - QueueConfigTable
          - QuickConnectDetailsTable
          - ConnectRoutingProfilesTable
      - 
        Label:
          default: "Bucket Configuration"
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix

Parameters:
  AmazonAccountType:
    Type : "String"
    AllowedValues : 
      - 'SAME_ACCOUNT'
      - 'ANOTHER_ACCOUNT'
    Description: "Select the account where you want to create the resources"
    ConstraintDescription: must select an correct AWS account.
    Default: "SAME_ACCOUNT"
  AmazonTargetAccount:
    Description: >
        [Optional] "Enter the Id of the target AWS account. Leave Empty If you have an account type SAME_ACCOUNT"
    Type: String
    ConstraintDescription: Account Number Must Be of Type Integer
  AmazonTargetAccountRegion:
    Description: >
        [Required When type 'ANOTHER_ACCOUNT' is Selected ] "Select the Region of the target AWS account. Ignore If you have an account type SAME_ACCOUNT"
    Type: String
    Default: "eu-west-2"
    AllowedValues : 
      - 'us-east-1'
      - 'us-east-2'
      - 'us-west-1'
      - 'us-west-2'
      - 'ap-east-1'
      - 'ap-south-1'
      - 'ap-northeast-2'
      - 'ap-southeast-1'
      - 'ap-southeast-2'
      - 'ap-northeast-1'
      - 'sa-east-1'
      - 'ca-central-1'
      - 'eu-central-1'
      - 'eu-west-1'
      - 'eu-west-2'
      - 'eu-west-3'
      - 'eu-north-1'
    ConstraintDescription: Please Select the Correct Region
  QueueConfigTable:
      Type: String
      Default:  "Queue_Config"
      Description: The name of the DynamoDB Table connect queue configurations will be backed up (Ensure you do not have a table with this name already).
  QuickConnectDetailsTable:
    Type: String
    Default:  "Quick_Connect_Details"
    Description: The name of the DynamoDB Table where quick connects will be backed up (Ensure you do not have a table with this name already).
  ConnectRoutingProfilesTable:
    Type: String
    Default:  "Connect_Routing_Profiles"
    Description: The name of the DynamoDB Table where routing profiles will be backed up (Ensure you do not have a table with this name already).
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Default: connect-automation-cloudformation-quickstart
    Description: "Default s3 bucket (Must be a valid bucket name)"
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    Default: templates/
    Description: "s3 prefix must end with forward slash (/)."
    Type: String

Conditions:
  UseAWSAccount: !Equals
      - !Ref AmazonAccountType
      - 'ANOTHER_ACCOUNT'
  UseSameAccount: !Equals
    - !Ref AmazonAccountType
    - 'SAME_ACCOUNT'
Rules:
  ValidateAWSAccount:
    RuleCondition: !Equals
      - !Ref AmazonAccountType
      - 'ANOTHER_ACCOUNT'
    Assertions:
      - Assert: !Not 
          - !Equals 
            - !Ref AmazonTargetAccount
            - ''
        AssertDescription: Amazon Target Account ID field cannot be empty if ANOTHER_ Account type is selected
Resources:
    CreateSameAccountStack:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}connect-template-source-account-1.yaml

    CrossRegionAccountStackSet:      
      Type: AWS::CloudFormation::StackSet
      Condition: UseAWSAccount
      DependsOn : CreateSameAccountStack
      Properties:
        StackSetName: CrossRegionAccountStackSet
        PermissionModel: SELF_MANAGED
        StackInstancesGroup:
          - Regions:
              - !Ref AmazonTargetAccountRegion
            DeploymentTargets:
              Accounts:
                - !Ref AmazonTargetAccount
        TemplateURL: !Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}create-ddb-tables.yaml
        Parameters:
          - ParameterKey: QueueConfig
            ParameterValue: !Ref QueueConfigTable
          - ParameterKey: QuickConnectDetails
            ParameterValue: !Ref QuickConnectDetailsTable
          - ParameterKey: ConnectRoutingProfiles
            ParameterValue: !Ref ConnectRoutingProfilesTable