AWSTemplateFormatVersion: 2010-09-09
Description: >
  Amazon Cross Account IAM Role Creation

Parameters:
  AmazonTargetAccountID:
    Type: String
    Description: Enter the Id of the target AWS account. Leave Empty If you have an account type SAME_ACCOUNT

Resources:       
    CrossAccountIAMRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - 
              Action: sts:AssumeRole
              Effect: Allow
              Principal:
                AWS:
                  Fn::Sub: arn:aws:iam::${AmazonTargetAccount}:root              
              Sid: 'CrossAccount1'
        Path: "/"
        ManagedPolicyArns:
          - 
            arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        RoleName : AmazonCrossAccountRoleAccess
    
    CrossAccountIAMRolePolicies:
      Type: "AWS::IAM::Policy"
      Properties:
        PolicyName: "AmazonCrossAccountAcessRole"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action: "*"
              Resource: "*"
        Roles:
          - Ref: "CrossAccountIAMRole"
