AWSTemplateFormatVersion: 2010-09-09
Description: >
  Amazon Connect Cloud Contact Center Operations
 
Parameters:
  S3BucketForWebSiteAssets:
    Type: String
    Default:  "contact-api-dashboard"
    AllowedPattern: '(?=^.{3,63}$)(?!^(\d+\.)+\d+$)(^(([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])\.)*([a-z0-9]|[a-z0-9][a-z0-9\-]*[a-z0-9])$)'
    ConstraintDescription: 'Invalid S3 Bucket name'
    Description: Enter the (globally unique) name you would like to use for the Amazon S3 bucket where we will store the website assets and the sample contact flow. This template will fail to deploy if the bucket name you chose is currently in use.

  BackupDDBTable:
    Type: String
    Default:  "ConnectFlows"
    Description: >
        The name of the DynamoDB Table contact flows will be backed up (Ensure you do not have a table with this name already).

  arnMappingDDBTable:
    Type: String
    Default:  "contactflowmapping"
    Description: >
        The name of the DynamoDB Table which maintains ARN mappings to target environment (Ensure you do not have a table with this name already).

Resources:
    ConnectBackupDDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName:  !Ref BackupDDBTable
        AttributeDefinitions:
          -
            AttributeName: "flowId"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "flowId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

    CFAARNMappingDDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName:  !Ref arnMappingDDBTable
        AttributeDefinitions:
          -
            AttributeName: "sourceARN"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "sourceARN"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST

Outputs:
  CloudfrontEndpoint:
      Description: Endpoint for Cloudfront distribution
      Value: !Join
        - ''
        - - 'https://'
          - !GetAtt [CFCloudFrontDistribution, DomainName]
          - '/<file-name>'
  
  DDBForBackup:
      Description: Backup DynamoDB Table 
      Value: !Ref BackupDDBTable
      
  DDBForARNMapping:
      Description: ARN Mapping of the DynamoDB Table.
      Value: !Ref arnMappingDDBTable