AWSTemplateFormatVersion: 2010-09-09
Description: >
  Amazon IAM Roles Creation For StackSet Implementation

Parameters:
  SourceAccountId:
    Type: String
    Description: Enter The Account ID througth you want to give permission to run stacksets.
  AdministrationRoleARNForStackset:
    Type: String
    Description: Enter The Name of the AWS CloudFormation StackSet Administration Role.

Resources:  
  AWSCloudFormationStackSetExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${SourceAccountId}:role/${AdministrationRoleARNForStackset}"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: AWSCloudFormationStackSetExecutionRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: 
                  - "dynamodb:BatchGetItem"
                  - "dynamodb:BatchWriteItem"
                  - "dynamodb:ConditionCheckItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:DescribeTable"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:Scan"
                  - "dynamodb:Query"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:UpdateTable"
                  - "dynamodb:ListTables"
                  - "dynamodb:CreateTable"
                  - "dynamodb:CreateTableReplica"
                  - "dynamodb:DeleteTable"
                Resource: "*"
              - Effect: "Allow"
                Action: "cloudformation:*"
                Resource: "*"
              - Effect: "Allow"
                Action: "s3:*"
                Resource: "*"
              - Effect: "Allow"
                Action: "sns:*"
                Resource: "*"
              - Effect: "Allow"
                Action: "lambda:InvokeFunction"
                Resource: "*"